
const listOfCountries =
[
  'Afghanistan',
  'Åland Islands',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bonaire',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo',
  'Cook Islands',
  'Costa Rica',
  'Côte d\'Ivoire',
'Croatia',
  'Cuba',
  'Curaçao',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Malvinas',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Holy See',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea',
  'Kuwait',
  'Kyrgyzstan',
  'Lao People\'s Democratic Republic',
'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia',
  'Moldova, Republic of',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands, Kingdom of the',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'North Macedonia',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine, State of',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Réunion',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Saint Barthélemy',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin (French part)',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Dutch part)',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan, Province of China',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Türkiye',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Viet Nam',
  'Virgin Islands (British)',
  'Virgin Islands (U.S.)',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];

const List<String> activityNames = [
  'amusement parks',
  'animal encounters',
  'archaeological sites',
  'architecture photography',
  'architecture tours',
  'art classes',
  'arts and culture',
  'ayurvedic spa treatments',
  'beach visits',
  'beachfront dining',
  'bird watching',
  'boat safaris',
  'botanical gardens',
  'butterfly watching',
  'camping',
  'caving',
  'city tours',
  'craft workshops',
  'cultural experiences',
  'cultural festivals',
  'cycling',
  'elephant rides',
  'fishing',
  'golfing',
  'hiking',
  'historic sites',
  'historic walks',
  'historical monuments',
  'history tours',
  'horse shows',
  'horseback riding',
  'hot air ballooning',
  'hot springs',
  'kayaking',
  'landscape photography',
  'literary tours',
  'local crafts',
  'mountain biking',
  'museum visits',
  'outdoor adventures',
  'paddleboarding',
  'photography',
  'planetarium visits',
  'public art installations',
  'river cruises',
  'rock climbing',
  'safaris',
  'sailing',
  'sailing lessons',
  'scuba diving',
  'sea cruises',
  'sightseeing',
  'snorkeling',
  'spiritual retreats',
  'surfing',
  'tea tasting',
  'temple pilgrimages',
  'theater',
  'themed parks',
  'traditional ceremonies',
  'turtle watching',
  'village homestays',
  'water parks',
  'waterfalls',
  'whale watching',
  'wildlife viewing',
  'yoga retreats',
  'zip-lining',
];

const List<String> bucketListNames = [
  "Ahangama",
  "Ahungalla",
  "Ambalangoda",
  "Ambalangoda Mask Workshop",
  "Ambuluwawa Tower",
  "Anawilundawa Wetlands",
  // "Anuradapura",
  "Anuradhapura",
  "Arankelle Forest Monastery",
  "Arugam Bay Beach",
  "Baker's Falls",
  "Bambarakanda Falls",
  "Bambarakiri Ella",
  "Batadombalena Craft Centre",
  "Batatotalena (Batadombalena) Cave",
  "Belihuloya",
  "Belilena Caves",
  "Bentota",
  "Bentota Beach",
  "Bentota River",
  "Bolgoda Lake",
  "Bomburu Ella Waterfall",
  "Bopath Falls",
  "Bundala National Park",
  "Colombo",
  "Colombo City Tour",
  "Colombo National Museum",
  "Colombo Port City",
  "Dambulla",
  "Dambulla Royal Cave Temple and Golden Temple",
  "Devon Falls",
  "Diyaluma Falls",
  "Dry Zone Botanic Gardens, Hambantota",
  "Dunhinda Waterfall",
  "Dutch Museum",
  "Elephant Transit Home",
  "Ella",
  "Ella Gap",
  "Ella Rock",
  "Excel World",
  "Folk Museum",
  "Galle",
  "Galle City Tour",
  "Galle Dutch Fort",
  "Galle Fort",
  "Galle Lighthouse",
  "Gangaramaya Temple",
  "Hakgala Botanical Garden",
  "Haputale",
  "Hatton",
  "Hikkaduwa",
  "Hikkaduwa Beach",
  "Hikkaduwa Coral Sanctuary",
  "Hiriketiya",
  "Hiriketiya Beach",
  "Horton Plains",
  "Horton Plains National Park",
  "Jaffna Public Library",
  "Jaya Sri Maha Bodhi",
  "Jungle Beach",
  // "Jungle beach",
  "Kalpitiya",
  "Kalpitiya Lagoon",
  "Kandalama",
  "Kandy",
  "Kandy City Centre",
  "Kandy Lake",
  "Kandy National Museum",
  "Kandy Temple",
  "Kanneliya National Rain Forest Reserve",
  "Kanniya Hot Springs",
  "Kithulgala",
  "Kitugala Forest",
  "Kitulgala",
  "Knuckles",
  "Koggala Beach",
  "Kosgoda Turtle Hatchery",
  "Kumana National Park",
  "Laxapana Falls",
  "Leisure World",
  "Lionel Wendt Art Centre",
  "Madu River",
  "Madunagala Hot Water Spring",
  "Maha Oya Hot Water Springs",
  "Mahalenama Cave",
  "Mahapelessa Hot Springs",
  "Marakolliya Beach",
  "Maritime Museum",
  "Martin Wickramasinghe Folk Museum",
  "Meemure",
  "Mihintale",
  "Minneriya National Park",
  "Mirissa Beach",
  "Museum of Modern and Contemporary Art",
  "Nallur Kandaswamy Devasthanam",
  "Nallur Kandaswamy Kovil",
  "National Gallery of Art",
  "National Museum Galle",
  "Negambo",
  "Negombo",
  "Negombo Lagoon",
  "Nelum Pokuna Theatre",
  "Nelung Arts Centre",
  "Nilaveli Beach",
  "Nine Arches Bridge",
  "Nuwara Eliya",
  "Nuwara Eliya Golf Club",
  "Passikuda Beach",
  "Pearl Bay",
  // "Perl Bay",
  "Pidurangala Rock",
  "Pigeon Island",
  "Pinnawala",
  "Pinnawala Elephant Orphanage",
  // "Polonaruwa",
  "Polonnaruwa",
  "Polonnaruwa Ancient City",
  "Ramboda Falls",
  "Ratnapura Gem Museum",
  "Ravan Ella Waterfall",
  "Rekawa Beach",
  "Ritigala",
  "Riverstone Gap",
  "Royal Botanical Gardens, Peradeniya",
  "Royal Colombo Golf Club",
  "Ruhunu Maha Kataragama Dewalaya",
  "Seetha Eliya",
  "Seethawaka Wet Zone Botanical Gardens",
  "Sigiriya",
  "Sinharaja Forest Reserve",
  "Sri Dalada Maligawa",
  "Sri Lanka Planetarium",
  "Sri Pada / Adam's Peak",
  "St Clair's Falls",
  "Surathali Ella",
  "Tangalle",
  "Tangalle Beach",
  "Trincomalee",
  "Trincomalee Harbour",
  "Udawalawe",
  "Udawalawe National Park",
  "Unawatuna",
  "Unawatuna Beach",
  "Unawatuna Lagoon",
  "Uppuveli Beach",
  "Vaddha Village Camping",
  "Velgam Vehera Buddhist Temple",
  "Victoria Golf Club",
  "Viharamahadevi Park",
  "Wasgamuwa National Park",
  "Water World Lanka",
  "Wavulpone Cave",
  "Weligama Beach",
  "Weligama Beach (surf and stay)",
  "Wilpattu National Park",
  "Yala National Park",
  "Yapahuwa Rock Fortress",
];